name: Unicode Releases
description: GitHub Action for gathering information about Unicode releases, including the latest release, current draft, and UCD (Unicode Character Database) releases.

author: Lucas Nørgård
branding:
  color: blue
  icon: globe

inputs:
  api_base_url:
    description: "The base URL for API, e.g. 'https://api.ucdjs.dev' or 'https://preview.api.ucdjs.dev'"
    default: "https://api.ucdjs.dev"
  proxy_base_url:
    description: "The base URL for the proxy server, e.g. 'https://unicode-proxy.ucdjs.dev' or 'https://preview.unicode-proxy.ucdjs.dev'"
    default: "https://unicode-proxy.ucdjs.dev"

outputs:
  all_releases:
    description: 'JSON array of all Unicode release names'
    value: ${{ steps.unicode-releases.outputs.all_releases }}
  latest_release:
    description: 'The latest Unicode release information'
    value: ${{ steps.unicode-releases.outputs.latest_release }}
  current_draft:
    description: 'The current draft Unicode release information'
    value: ${{ steps.unicode-releases.outputs.current_draft }}
  ucd_releases:
    description: 'JSON array of UCD release names'
    value: ${{ steps.unicode-releases.outputs.ucd_releases }}

# Note:
# - inputs.* should be manually mapped to INPUT_* due to https://github.com/actions/runner/issues/665
# - Use GITHUB_*/RUNNER_* instead of github.*/runner.* due to https://github.com/actions/runner/issues/2185
runs:
  using: composite
  steps:
    - id: unicode-releases
      env:
        INPUT_API_BASE_URL: ${{ inputs.api_base_url }}
        INPUT_PROXY_BASE_URL: ${{ inputs.proxy_base_url }}
      run: bash --noprofile --norc "${GITHUB_ACTION_PATH:?}/run.sh"
      shell: bash
