name: Unicode Releases
description: "GitHub Action to gather Unicode information: latest release, current draft, and Unicode releases."

author: Lucas Nørgård
branding:
  color: blue
  icon: globe

inputs:
  api_base_url:
    description: "The base URL for API, e.g. 'https://api.ucdjs.dev' or 'https://preview.api.ucdjs.dev'"
    default: "https://api.ucdjs.dev"

outputs:
  all_releases:
    description: 'JSON array of all Unicode release names'
    value: ${{ steps.unicode-releases.outputs.all_releases }}
  latest_release:
    description: 'The latest Unicode release information'
    value: ${{ steps.unicode-releases.outputs.latest_release }}
  current_draft:
    description: 'The current draft Unicode release information'
    value: ${{ steps.unicode-releases.outputs.current_draft }}

# Note:
# - inputs.* should be manually mapped to INPUT_* due to https://github.com/actions/runner/issues/665
# - Use GITHUB_*/RUNNER_* instead of github.*/runner.* due to https://github.com/actions/runner/issues/2185
runs:
  using: composite
  steps:
    - id: unicode-releases
      env:
        INPUT_API_BASE_URL: ${{ inputs.api_base_url }}
      run: bash --noprofile --norc "${GITHUB_ACTION_PATH:?}/run.sh"
      shell: bash
